### ISSUE TITLE
Cannot run code!

### ISSUE THREAD

**Issue by sagar1garg** [mcahny/Deep-Video-Inpainting#15]
@SeokjuLee @mcahny 
Getting this error when trying to run !bash install.sh :

Compiling resample2d kernels by nvcc...
rm: cannot remove 'Resample2d_kernel.o': No such file or directory
rm: cannot remove '../_ext': No such file or directory
In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/host_config.h:50:0,
                 from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
x86_64-linux-gnu-gcc: error: /content/Deep-Video-Inpainting/lib/resample2d_package/src/Resample2d_kernel.o: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 209, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/local/lib/python3.6/dist-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/usr/local/lib/python3.6/dist-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python3.6/dist-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Compiling correlation kernels by nvcc...
rm: cannot remove 'correlation_cuda_kernel.o': No such file or directory
rm: cannot remove '../_ext': No such file or directory
In file included from /usr/local/cuda/bin/../targets/x86_64-linux/include/host_config.h:50:0,
                 from /usr/local/cuda/bin/../targets/x86_64-linux/include/cuda_runtime.h:78,
                 from <command-line>:0:
/usr/local/cuda/bin/../targets/x86_64-linux/include/crt/host_config.h:119:2: error: #error -- unsupported GNU version! gcc versions later than 6 are not supported!
 #error -- unsupported GNU version! gcc versions later than 6 are not supported!
  ^~~~~
x86_64-linux-gnu-gcc: error: /content/Deep-Video-Inpainting/models/correlation_package/src/correlation_cuda_kernel.o: No such file or directory
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 209, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 31, in <module>
    ffi.build()
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 184, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python3.6/dist-packages/torch/utils/ffi/__init__.py", line 108, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/local/lib/python3.6/dist-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/local/lib/python3.6/dist-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/usr/local/lib/python3.6/dist-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python3.6/dist-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by mahbubcseju** [comment]
@sagar1garg  Have you succeeded to install  the project ? I am getting the similar error. I am trying to install without CUDA and GPU .

**Comment by ulatekh** [comment]
The error is pretty clear...

"#error -- unsupported GNU version! gcc versions later than 6 are not supported!"

nVidia CUDA is notorious for only supporting specific versions of gcc.
This is a CUDA issue, not specific to the Deep-Video-Inpainting project.

**Comment by kedarSedai** [comment]
Do you need to install CUDA for this Project?

**Comment by ulatekh** [comment]
> Do we need to install CUDA for this Project?

Yes.

**Comment by mcahny** [comment]
@[sagar1garg ](https://github.com/sagar1garg)
Please check the latest update with Pytorch1.4 and Cuda10.0. Thanks.
