### ISSUE TITLE
demo_vi.py ERROR

### ISSUE THREAD

**Issue by aschneid42** [mcahny/Deep-Video-Inpainting#19]
I got the first step, 1) Compile Resample2d, Correlation dependencies, complete by using the versions from the flownet2 repo, but can't seem to get the demo_vi.py script to run. 

python demo_vi.py
Model name should be: vinet_final
Traceback (most recent call last):
  File "demo_vi.py", line 75, in <module>
    model, _ = generate_model(opt)
  File "/persistent_data/home/ad006850/Deep-Video-Inpainting-master/model.py", line 15, in generate_model
    model = model.cuda()
UnboundLocalError: local variable 'model' referenced before assignment

My version of torch is 1.0.0, and CUDA is 10.0.  Not sure if these versions could be the issue...

**Comment by ulatekh** [comment]
https://github.com/mcahny/Deep-Video-Inpainting says to use PyTorch 0.4.0 .
