### ISSUE TITLE
have a problem when bash install.sh

### ISSUE THREAD

**Issue by OnlyFlashEobard** [mcahny/Deep-Video-Inpainting#29]
when bash install.sh by conda envs
I meet a issue(it seems like i need to set a PATH for CUDA but i don't know how to set it for conda envs):
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/home/mobax/anaconda3/envs/vinet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/mobax/anaconda3/envs/vinet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/mobax/anaconda3/envs/vinet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    ], extra_compile_args={'cxx': cxx_args, 'nvcc': nvcc_args})
  File "/home/mobax/anaconda3/envs/vinet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 498, in CUDAExtension
    library_dirs += library_paths(cuda=True)
  File "/home/mobax/anaconda3/envs/vinet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 577, in library_paths
    if (not os.path.exists(_join_cuda_home(lib_dir)) and
  File "/home/mobax/anaconda3/envs/vinet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1252, in _join_cuda_home
    raise EnvironmentError('CUDA_HOME environment variable is not set. '
OSError: CUDA_HOME environment variable is not set. Please set it to your CUDA install root.

**Comment by outfielder** [comment]
I also have this problem. Did you manage to fix it?

**Comment by iimrann412** [comment]
you can open the file the in notepad and install the library manually but there is one problem in building dist file i odn;t know the alternate comman tfor buidling dist files

**Comment by Deerzh** [comment]
I have this problem too, who can help me

**Comment by HiFei2057** [comment]
@OnlyFlashEobard @outfielder @Deerzh
You can modify `.bashrc` like this:
`sudo vi ~/.bashrc`
`CUDA_HOME=/usr/local/cuda-X.X`
`X.X` is your CUDA version, you can use `nvcc --version` to check the version and replace it in the command
Give it a try.
